name: Test suite

on:
  workflow_dispatch:
  pull_request:
    branches: ['develop']
    paths:
      - .github/workflows/testsuite.yml
      - superdsm/**
      - examples/**
      - superdsm.yml
      - tests/**
      - requirements.txt

jobs:

  run_testsuite:
    name: Test suite
    runs-on: self-hosted
    container:
      image: ubuntu:20.04
    defaults:
      run:
        shell: bash -el {0}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.8.5'
        env:
          PIP_TRUSTED_HOST: "pypi.python.org pypi.org files.pythonhosted.org"

      - name: Install dependencies
        run: pip install -r requirements.txt
          
      - name: Run SuperDSM
        run: python -m "unittest"
