name: Test suite

on:
  workflow_dispatch:
  pull_request:
    branches: ['develop']
    paths:
      - .github/workflows/testsuite.yml
      - superdsm/**
      - examples/**
      - superdsm.yml
      - tests/**
      - requirements.txt

jobs:

  run_testsuite:
    name: Test suite
    runs-on: gpuagrohr-01
    container:
      image: ubuntu:22.04
    defaults:
      run:
        shell: bash -el {0}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Clear cache  # otherwise corrupted packages can be reported sometimes
        run: rm -rf /github/home/conda_pkgs_dir

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          channels: conda-forge, bioconda, defaults
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: superdsm
          environment-file: superdsm.yml

      - name: Run SuperDSM
        run: python -m "unittest"
