name: Test suite

on:
  workflow_dispatch:
  pull_request:
    branches: ['develop']
    paths:
      - .github/workflows/testsuite.yml
      - superdsm/**
      - examples/**
      - superdsm.yml
      - tests/**
      - requirements.txt

jobs:

  run_testsuite:
    name: Test suite
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
    defaults:
      run:
        shell: bash -el {0}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.8.12'

      - name: Install dependencies
        run: |
          sudo apt-get install sqlite3 libsqlite3-dev
          pip install -r requirements.txt

      - name: Debug
        run: pip list
          
      - name: Run SuperDSM
        run: python -m "unittest"
