name: Validate pull request

on:
  pull_request:

jobs:

  validate_branches:
    name: Validate branches
    runs-on: ubuntu-latest

    steps:

      - name: Validate branches
        if: github.base_ref == 'master' && github.head_ref != 'develop'
        run: |
          echo "Contributions should be made against the develop branch, see README.rst."
          exit 1

  validate_conditional_checks:
    name: Validate conditional checks
    timeout-minutes: 1440
    runs-on: gpuagrohr-02
#    container:
#      image: ubuntu:22.04

    steps:
    
      - uses: blend/require-conditional-status-checks@2022.02.04
        with:
          interval: 20s
          timeout: 1440m
          checks-yaml: |
            - job: 'Test: U2OS'
              paths:
                - .github/workflows/regressiontests.yml
                - superdsm/**
                - examples/**
                - superdsm.yml
                - tests/regression
            - job: 'Test: NIH3T3'
              paths:
                - .github/workflows/regressiontests.yml
                - superdsm/**
                - examples/**
                - superdsm.yml
                - tests/regression
            - job: 'Test: GOWT1-1'
              paths:
                - .github/workflows/regressiontests.yml
                - superdsm/**
                - examples/**
                - superdsm.yml
                - tests/regression
            - job: 'Test: GOWT1-2'
              paths:
                - .github/workflows/regressiontests.yml
                - superdsm/**
                - examples/**
                - superdsm.yml
                - tests/regression
            - job: 'Test suite'
              paths:
                - .github/workflows/testsuite.yml
                - superdsm/**
                - examples/**
                - superdsm.yml
                - tests/**
